### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by kjlyon** [rkoeze/react-mock-router#2]
Hello @rkoeze , I would like to use your mock router in my project. Can you please provide a license file so that I can reference it and make sure I'm not breaking any legal boundaries within my company. 

A simple license to add is the [MIT License](https://opensource.org/licenses/MIT). A great example of this in use is [here](https://github.com/sensu/sensu/blob/master/MIT-LICENSE.txt).

Thank you

**Comment by rkoeze** [comment]
I'll have one up by the end of the day. Thanks!

**Comment by kjlyon** [comment]
Awesome! Thank you so much!

**Comment by rkoeze** [comment]
Done!
